### PR TITLE
Added OpenMP farm implementation with consumer function object - issue 178

### PR DESCRIPTION
**Pull request by Drioastorga**
Added the version of the farm interface with three function objects for OpenMP. Additionally, the typenames of the function objects of the farm interfaces have been renamed.

### CODE REVIEW

**Review by jdgarciauc3m — APPROVED** [review]
OK

**Review by jdgarciauc3m — CHANGES_REQUESTED** [review]
There are conflicts with latest.

We need to solve before merging.

**Comment by Drioastorga** [comment]
Conflicts have been solved. Additionally, there is a new example of the farm function using a consumer function.

**Review by jdgarciauc3m — APPROVED** [review]
OK

**Comment by jdgarciauc3m** [comment]
Solves issue #178

**Pull request merged**
