### PR TITLE
Add unit tests for stream filter - Issue 98

### PR DESCRIPTION
**Pull request by mdolz**
Added unit tests for the stream_filter pattern. Poly tests are commented.

### CODE REVIEW

**Review by jdgarciauc3m — CHANGES_REQUESTED** [review]
Pull requests to master are not allowed.

Please make a pull request against latest.

**Review by jdgarciauc3m — CHANGES_REQUESTED** [review]
Some unit tests do not pass:

The following tests FAILED:
	 10 - stream_filter_test/*.static_single_filtered_composed (SEGFAULT)
	 11 - stream_filter_test/*.static_single_unfiltered_composed (SEGFAULT)
	 12 - stream_filter_test/*.static_multiple_composed (SEGFAULT)

**Comment by mdolz** [comment]
Segmentation faults of the stream filter unit tests have been fixed.

**Review by jdgarciauc3m — APPROVED** [review]
OK

**Comment by jdgarciauc3m** [comment]
Solves issue #98

**Pull request merged**
