### PR TITLE
Modified  divide and conquer interface - Issue 123

### PR DESCRIPTION
**Pull request by Drioastorga**
Updated version for the divide and conquer pattern.

Changes:
- The intial value is taken by value.
- Now the output is returned instead of be taken by reference.
- The base problem operation should only take a single argument for the problem and return the result. 
- Removed unnecessary commented code.

### CODE REVIEW

**Review by jdgarciauc3m — CHANGES_REQUESTED** [review]
Why do we need to pass input by value?

Is passing an initial value really needed?

**Comment by Drioastorga** [comment]
I have removed the initial value from the divide and conquer interface since it is not required anymore.

**Review by jdgarciauc3m — APPROVED** [review]
OK

**Comment by jdgarciauc3m** [comment]
Solves issue #123

**Pull request merged**
