### PR TITLE
Removed External deps download

### PR DESCRIPTION
**Pull request by jdgarciauc3m**
Managing dependencies with ExternalProject_Add was becoming increasingly complex. Besides it is not the most appropriate way of doing.

New approach:
- Require GTest only when GRPPI_UNIT_TEST_ENABLE is ON. If GTest is not found, the GRPPI_UNIT_TEST_ENABLE is set to OFF.
- The GTest Requirement is only needed in case you want to get unit tests.
- If FastFlow is not found GRPPI_FF_ENABLE is set to OFF

### CODE REVIEW

**Review by Drioastorga — COMMENTED** [review]
Compiling the legacy unit test emits error messages due to the deprecated warning. I suggest to remove these tests from the unit test suite to avoid these error messages.

**Comment by jdgarciauc3m** [comment]
Please note that the deprecated  issue is solved bye pr #338 .

Is there any other issue or can we accept this one?

**Review by javiergarcia — DISMISSED** [review]
Better to remove this feature and rely on system packages.

**Review by Drioastorga — DISMISSED** [review]
Ok

**Pull request merged**
