### PR TITLE
Added support for offsets bigger than windows - issue 246

### PR DESCRIPTION
**Pull request by Drioastorga**
Added support for using a offset bigger than the window size for all the backends.

### CODE REVIEW

**Review by mdolz — DISMISSED** [review]
Ok.

**Review by javidoc00 — DISMISSED** [review]

**Review by jdgarciauc3m — CHANGES_REQUESTED** [review]
This PR should also contain:

* The update of the example.
* More unit tests to ensure coverage.

**Comment by Drioastorga** [comment]
I have added two new test for the stream reduce.

**Review by jdgarciauc3m — APPROVED** [review]
OK

**Comment by jdgarciauc3m** [comment]
Solves issue #246

**Pull request merged**
