### PR TITLE
Modified composed stream reduce interface - Issue 239

### PR DESCRIPTION
**Pull request by Drioastorga**
I have modified the interface of the stream reduce in order to align this interface with its stand-alone version. Currently, this composition is only supported by OpenMP and native execution policies.

### CODE REVIEW

**Review by jdgarciauc3m — CHANGES_REQUESTED** [review]
Unresolved confilct in file include/native/pipeline.h

**Comment by Drioastorga** [comment]
Fixed.

**Review by jdgarciauc3m — APPROVED** [review]
OK

**Review by jdgarciauc3m — CHANGES_REQUESTED** [review]
There is a compilation error when compiling file `stream_iteration_pipe.cpp`. Please, solve it.

**Comment by Drioastorga** [comment]
Fixed

**Review by jdgarciauc3m — APPROVED** [review]
OK

**Review by mdolz — APPROVED** [review]
Ok.

**Review by javidoc00 — APPROVED** [review]

**Comment by jdgarciauc3m** [comment]
Solves issue #239

**Pull request merged**
