### PR TITLE
Replaced push_back(thread{T}) by emplace_back(T) - Issue 233

### PR DESCRIPTION
**Pull request by mdolz**
Replaced push_back(thread{T}) by emplace_back(T)

### CODE REVIEW

**Review by jdgarciauc3m — CHANGES_REQUESTED** [review]
In all cases:

1.- The lambda should be opened in the same line than x.emplace_back(

~~~c++
tasks.emplace_back([&](int i, int j) {
  code
});
~~~

Ta is legible and compact.

2. Follow the current indenting in the code (two spaces per indentation level).

**Comment by mdolz** [comment]
Fixed indentation.

**Review by jdgarciauc3m — APPROVED** [review]
OK

**Comment by jdgarciauc3m** [comment]
Solves issue #233

**Pull request merged**
