### PR TITLE
Included stencil with multiple inputs - issue 213

### PR DESCRIPTION
**Pull request by mdolz**
We decided that the neighborhood function should receive all the inputs and generate a collection of neighborhoods. With this, the transform function takes as input the current iterator and the aforementioned collection of neighborhoods. Finally, we have included the corresponding unit tests.

### CODE REVIEW

**Comment by Drioastorga** [comment]
Fixed bug in stencil with multiple inputs.

**Comment by jdgarciauc3m** [comment]
The following unit tests fail:

The following tests FAILED:
	124 - stencil_test/*.static_multiple_ary (Failed)
	127 - stencil_test/*.poly_multiple_ary (Failed)

Detailed output

~~~
Running main() from gtest_main.cc
Note: Google Test filter = stencil_test/*
[==========] Running 48 tests from 4 test cases.
[----------] Global test environment set-up.
[----------] 12 tests from stencil_test/0, where TypeParam = grppi::sequential_execution
[ RUN      ] stencil_test/0.static_empty
[       OK ] stencil_test/0.static_empty (0 ms)
[ RUN      ] stencil_test/0.poly_empty
[       OK ] stencil_test/0.poly_empty (0 ms)
[ RUN      ] stencil_test/0.static_single
[       OK ] stencil_test/0.static_single (0 ms)
[ RUN      ] stencil_test/0.poly_single
[       OK ] stencil_test/0.poly_single (0 ms)
[ RUN      ] stencil_test/0.static_multiple
[       OK ] stencil_test/0.static_multiple (0 ms)
[ RUN      ] stencil_test/0.poly_multiple
[       OK ] stencil_test/0.poly_multiple (0 ms)
[ RUN      ] stencil_test/0.static_empty_ary
[       OK ] stencil_test/0.static_empty_ary (0 ms)
[ RUN      ] stencil_test/0.static_single_ary
[       OK ] stencil_test/0.static_single_ary (1 ms)
[ RUN      ] stencil_test/0.static_multiple_ary
/home/jdgarcia/repos/github/arcosuc3m/grppi/unit_tests/stencil.cpp:107: Failure
      Expected: 54
To be equal to: invocations_operation
      Which is: 9
/home/jdgarcia/repos/github/arcosuc3m/grppi/unit_tests/stencil.cpp:108: Failure
      Expected: 54
To be equal to: invocations_neighbour
      Which is: 9
[  FAILED  ] stencil_test/0.static_multiple_ary, where TypeParam = grppi::sequential_execution (0 ms)
[ RUN      ] stencil_test/0.poly_empty_ary
[       OK ] stencil_test/0.poly_empty_ary (0 ms)
[ RUN      ] stencil_test/0.poly_single_ary
[       OK ] stencil_test/0.poly_single_ary (0 ms)
[ RUN      ] stencil_test/0.poly_multiple_ary
/home/jdgarcia/repos/github/arcosuc3m/grppi/unit_tests/stencil.cpp:107: Failure
      Expected: 54
To be equal to: invocations_operation
      Which is: 9
/home/jdgarcia/repos/github/arcosuc3m/grppi/unit_tests/stencil.cpp:108: Failure
      Expected: 54
To be equal to: invocations_neighbour
      Which is: 9
[  FAILED  ] stencil_test/0.poly_multiple_ary, where TypeParam = grppi::sequential_execution (0 ms)
[----------] 12 tests from stencil_test/0 (1 ms total)

[----------] 12 tests from stencil_test/1, where TypeParam = grppi::parallel_execution_native
[ RUN      ] stencil_test/1.static_empty
[       OK ] stencil_test/1.static_empty (23 ms)
[ RUN      ] stencil_test/1.poly_empty
[       OK ] stencil_test/1.poly_empty (2 ms)
[ RUN      ] stencil_test/1.static_single
[       OK ] stencil_test/1.static_single (1 ms)
[ RUN      ] stencil_test/1.poly_single
[       OK ] stencil_test/1.poly_single (1 ms)
[ RUN      ] stencil_test/1.static_multiple
[       OK ] stencil_test/1.static_multiple (1 ms)
[ RUN      ] stencil_test/1.poly_multiple
[       OK ] stencil_test/1.poly_multiple (1 ms)
[ RUN      ] stencil_test/1.static_empty_ary
[       OK ] stencil_test/1.static_empty_ary (1 ms)
[ RUN      ] stencil_test/1.static_single_ary
[       OK ] stencil_test/1.static_single_ary (1 ms)
[ RUN      ] stencil_test/1.static_multiple_ary
/home/jdgarcia/repos/github/arcosuc3m/grppi/unit_tests/stencil.cpp:107: Failure
      Expected: 54
To be equal to: invocations_operation
      Which is: 9
/home/jdgarcia/repos/github/arcosuc3m/grppi/unit_tests/stencil.cpp:108: Failure
      Expected: 54
To be equal to: invocations_neighbour
      Which is: 9
[  FAILED  ] stencil_test/1.static_multiple_ary, where TypeParam = grppi::parallel_execution_native (1 ms)
[ RUN      ] stencil_test/1.poly_empty_ary
[       OK ] stencil_test/1.poly_empty_ary (0 ms)
[ RUN      ] stencil_test/1.poly_single_ary
[       OK ] stencil_test/1.poly_single_ary (1 ms)
[ RUN      ] stencil_test/1.poly_multiple_ary
/home/jdgarcia/repos/github/arcosuc3m/grppi/unit_tests/stencil.cpp:107: Failure
      Expected: 54
To be equal to: invocations_operation
      Which is: 9
/home/jdgarcia/repos/github/arcosuc3m/grppi/unit_tests/stencil.cpp:108: Failure
      Expected: 54
To be equal to: invocations_neighbour
      Which is: 9
[  FAILED  ] stencil_test/1.poly_multiple_ary, where TypeParam = grppi::parallel_execution_native (1 ms)
[----------] 12 tests from stencil_test/1 (34 ms total)

[----------] 12 tests from stencil_test/2, where TypeParam = grppi::parallel_execution_omp
[ RUN      ] stencil_test/2.static_empty
[       OK ] stencil_test/2.static_empty (16 ms)
[ RUN      ] stencil_test/2.poly_empty
[       OK ] stencil_test/2.poly_empty (0 ms)
[ RUN      ] stencil_test/2.static_single
[       OK ] stencil_test/2.static_single (0 ms)
[ RUN      ] stencil_test/2.poly_single
[       OK ] stencil_test/2.poly_single (0 ms)
[ RUN      ] stencil_test/2.static_multiple
[       OK ] stencil_test/2.static_multiple (0 ms)
[ RUN      ] stencil_test/2.poly_multiple
[       OK ] stencil_test/2.poly_multiple (0 ms)
[ RUN      ] stencil_test/2.static_empty_ary
[       OK ] stencil_test/2.static_empty_ary (0 ms)
[ RUN      ] stencil_test/2.static_single_ary
[       OK ] stencil_test/2.static_single_ary (0 ms)
[ RUN      ] stencil_test/2.static_multiple_ary
/home/jdgarcia/repos/github/arcosuc3m/grppi/unit_tests/stencil.cpp:107: Failure
      Expected: 54
To be equal to: invocations_operation
      Which is: 9
/home/jdgarcia/repos/github/arcosuc3m/grppi/unit_tests/stencil.cpp:108: Failure
      Expected: 54
To be equal to: invocations_neighbour
      Which is: 9
[  FAILED  ] stencil_test/2.static_multiple_ary, where TypeParam = grppi::parallel_execution_omp (1 ms)
[ RUN      ] stencil_test/2.poly_empty_ary
[       OK ] stencil_test/2.poly_empty_ary (0 ms)
[ RUN      ] stencil_test/2.poly_single_ary
[       OK ] stencil_test/2.poly_single_ary (0 ms)
[ RUN      ] stencil_test/2.poly_multiple_ary
/home/jdgarcia/repos/github/arcosuc3m/grppi/unit_tests/stencil.cpp:107: Failure
      Expected: 54
To be equal to: invocations_operation
      Which is: 9
/home/jdgarcia/repos/github/arcosuc3m/grppi/unit_tests/stencil.cpp:108: Failure
      Expected: 54
To be equal to: invocations_neighbour
      Which is: 9
[  FAILED  ] stencil_test/2.poly_multiple_ary, where TypeParam = grppi::parallel_execution_omp (0 ms)
[----------] 12 tests from stencil_test/2 (17 ms total)

[----------] 12 tests from stencil_test/3, where TypeParam = grppi::parallel_execution_tbb
[ RUN      ] stencil_test/3.static_empty
[       OK ] stencil_test/3.static_empty (1 ms)
[ RUN      ] stencil_test/3.poly_empty
[       OK ] stencil_test/3.poly_empty (0 ms)
[ RUN      ] stencil_test/3.static_single
[       OK ] stencil_test/3.static_single (0 ms)
[ RUN      ] stencil_test/3.poly_single
[       OK ] stencil_test/3.poly_single (0 ms)
[ RUN      ] stencil_test/3.static_multiple
[       OK ] stencil_test/3.static_multiple (0 ms)
[ RUN      ] stencil_test/3.poly_multiple
[       OK ] stencil_test/3.poly_multiple (0 ms)
[ RUN      ] stencil_test/3.static_empty_ary
[       OK ] stencil_test/3.static_empty_ary (0 ms)
[ RUN      ] stencil_test/3.static_single_ary
[       OK ] stencil_test/3.static_single_ary (0 ms)
[ RUN      ] stencil_test/3.static_multiple_ary
/home/jdgarcia/repos/github/arcosuc3m/grppi/unit_tests/stencil.cpp:107: Failure
      Expected: 54
To be equal to: invocations_operation
      Which is: 9
/home/jdgarcia/repos/github/arcosuc3m/grppi/unit_tests/stencil.cpp:108: Failure
      Expected: 54
To be equal to: invocations_neighbour
      Which is: 9
[  FAILED  ] stencil_test/3.static_multiple_ary, where TypeParam = grppi::parallel_execution_tbb (0 ms)
[ RUN      ] stencil_test/3.poly_empty_ary
[       OK ] stencil_test/3.poly_empty_ary (0 ms)
[ RUN      ] stencil_test/3.poly_single_ary
[       OK ] stencil_test/3.poly_single_ary (0 ms)
[ RUN      ] stencil_test/3.poly_multiple_ary
/home/jdgarcia/repos/github/arcosuc3m/grppi/unit_tests/stencil.cpp:107: Failure
      Expected: 54
To be equal to: invocations_operation
      Which is: 9
/home/jdgarcia/repos/github/arcosuc3m/grppi/unit_tests/stencil.cpp:108: Failure
      Expected: 54
To be equal to: invocations_neighbour
      Which is: 9
[  FAILED  ] stencil_test/3.poly_multiple_ary, where TypeParam = grppi::parallel_execution_tbb (0 ms)
[----------] 12 tests from stencil_test/3 (2 ms total)

[----------] Global test environment tear-down
[==========] 48 tests from 4 test cases ran. (54 ms total)
[  PASSED  ] 40 tests.
[  FAILED  ] 8 tests, listed below:
[  FAILED  ] stencil_test/0.static_multiple_ary, where TypeParam = grppi::sequential_execution
[  FAILED  ] stencil_test/0.poly_multiple_ary, where TypeParam = grppi::sequential_execution
[  FAILED  ] stencil_test/1.static_multiple_ary, where TypeParam = grppi::parallel_execution_native
[  FAILED  ] stencil_test/1.poly_multiple_ary, where TypeParam = grppi::parallel_execution_native
[  FAILED  ] stencil_test/2.static_multiple_ary, where TypeParam = grppi::parallel_execution_omp
[  FAILED  ] stencil_test/2.poly_multiple_ary, where TypeParam = grppi::parallel_execution_omp
[  FAILED  ] stencil_test/3.static_multiple_ary, where TypeParam = grppi::parallel_execution_tbb
[  FAILED  ] stencil_test/3.poly_multiple_ary, where TypeParam = grppi::parallel_execution_tbb

 8 FAILED TESTS

~~~

**Comment by Drioastorga** [comment]
Fixed.

**Review by jdgarciauc3m — APPROVED** [review]
OK

**Comment by jdgarciauc3m** [comment]
Closes issue #213

**Pull request merged**
