### PR TITLE
Initial FF support + map pattern

### PR DESCRIPTION
**Pull request by jdgarciauc3m**
Make fasflow initial integration and support map pattern.

### CODE REVIEW

**Review by mdolz — CHANGES_REQUESTED** [review]
Map sample ("daxpy") does not work with FF back end. Please consider adding FF back end in samples/util/util.h.

**Review by Drioastorga — DISMISSED** [review]
Ok.

**Review by javidoc00 — CHANGES_REQUESTED** [review]
Please include the FF back-end on the grppi/samples/util/util.h file.

**Comment by jdgarciauc3m** [comment]
Requested changes have been addressed.

Please, check again.

**Review by Drioastorga — APPROVED** [review]
Ok.

**Review by javidoc00 — APPROVED** [review]

**Review by mdolz — COMMENTED** [review]
Ok.

**Review by mdolz — APPROVED** [review]

**Pull request merged**
