### PR TITLE
Fixed compilation issues in c++17

### PR DESCRIPTION
**Pull request by tete17**
This PR could address #365 it has only been tested on ubuntu 18 with clang 6.0, g++ 7.3.0 with c++14 and c++17.

Please @Jerry-MA check if this solves your problem

### CODE REVIEW

**Comment by Jerry-Ma** [comment]
WIth macOS 10.14 llvm clang 7.0 c++17, it fails with:

```
../grppi/include/common/meta.h:22:6: error: "C++ detection
      idiom not supported. Upgrade your C++ compiler"
#    error "C++ detection idiom not supported. Upgrade your C++ compiler"
```

After looking into the experimental/type_traits header, I found that clang does not define the macro `__cpp_lib_experimental_detect`, as contrary to gcc, thus the failure.

Do you know how to fix this?

**Comment by tete17** [comment]
:thinking: 
This is different than the error that you got before. Could you provide the full cmake/make to see exactly what is happening.

I think this has more to do with the implementation of the standard library that your compiler comes from than the compiler itself. In my case is the one installed with gcc 7.

Could you check which standard libary you have installed and in which version?
I will admit this is a bit away from my confort zone (macOS) but we will ge to bottom of this :smile:

**Comment by Jerry-Ma** [comment]
It is a different issue, and this error is indeed related to different implementation of the standard library. In fact, I've managed to get through this one by removing the usage of `__cpp_lib_experimental_detect`, because I don't need to retain the c++14 compatibility in my use-case.

The reason of this error is that, in GCC, the experimental/traits header defines the macro `__cpp_lib_experimental_detect`, but in the library that I use, which is installed via homebrew (`brew install llvm`), this macro is not defined. To be specific, the llvm package in homebrew installs llvm clang from this url https://releases.llvm.org/7.0.1

That being said, I am guessing that we can do an `#ifdef` check of the compiler in-use and when clang is detected we use some thing equivalent to `__cpp_lib_experimental_detect` in GCC.

As far as the error I described in issue #366 , it is related to interplay of TBB backend and std::optional in C++17, which will reveal after this error is fixed.

**Comment by tete17** [comment]
I have been doing some digging and according to https://en.cppreference.com/w/cpp/experimental/lib_extensions_2

The use of that macro was not correct.
Maybe this will fix your issues

**Comment by Jerry-Ma** [comment]
It does not work. If you take a look at the llvm libcxx experimental/type_traits header: http://llvm.org/viewvc/llvm-project/libcxx/trunk/include/experimental/type_traits?view=markup
you will find that macro is not defined, which is defined in gcc libstdc++ . Therefore, for clang, we have to come up with another way to test if detection idiom is supported. Or, we can by-pass the test for clang libc++, given that it is indeed implemented.

**Comment by tete17** [comment]
Ok so this has been some digging.

Aparently the idiom detection implementation in libc++ is not complete (https://libcxx.llvm.org/TS_deprecation.html)
but it is enough to do the job.

I also suggest you open a issue for libc++ to implement the macros `__cpp_lib_experimental_*` because even though they are optional they are quiet usefull. That is also the reason this macro was never defined since it it not complete.

I have written some bypass to enable the partial implementation

**Comment by tete17** [comment]
The fact that `__cpp_lib_experimental_detect` is optional can be read here:
 * http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4502.pdf Section 9.3
 * http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/n4617.pdf Section 1.6.2

**Comment by Jerry-Ma** [comment]
Thank you very much for the fix. This part now works, except one more small thing for clang which introduced the following error:
```
 /Users/ma/Codes/devs/grppi/unit_tests/context.cpp:704:41: error: must specify at
      least one argument for '...' parameter of variadic macro
      [-Werror,-Wgnu-zero-variadic-macro-arguments]
TYPED_TEST_CASE(context_test, executions);
```
This could be fixed in the CMakeLists.txt file with 
```
if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
     add_compile_options(-Wno-gnu-zero-variadic-macro-arguments)
endif()
```

The only remaining error is now the one described in #365. The error message goes as:
```
In file included from /Users/ma/Codes/devs/grppi/include/grppi.h:20:
In file included from /Users/ma/Codes/devs/grppi/include/dyn/dynamic_execution.h:21:
In file included from /Users/ma/Codes/devs/grppi/include/tbb/parallel_execution_tbb.h:30:
In file included from /usr/local/include/tbb/tbb.h:72:
/usr/local/include/tbb/pipeline.h:394:30: error: call to implicitly-deleted
      default constructor of
      'tbb::interface6::internal::token_helper<std::__1::optional<int>,
      false>::type_to_void_ptr_map'
        type_to_void_ptr_map mymap;
                             ^
/usr/local/include/tbb/pipeline.h:446:26: note: in instantiation of member
      function 'tbb::interface6::internal::token_helper<std::__1::optional<int>,
      false>::cast_to_void_ptr' requested here
        return u_helper::cast_to_void_ptr(output_u);
                         ^
/usr/local/include/tbb/pipeline.h:450:5: note: in instantiation of member
      function 'tbb::interface6::internal::concrete_filter<void,
      std::__1::optional<int>, (lambda at
      /Users/ma/Codes/devs/grppi/include/tbb/parallel_execution_tbb.h:692:5)>::operator()'
      requested here
    concrete_filter(tbb::filter::mode filter_mode, const Body& body) :
    ^
/usr/local/include/tbb/pipeline.h:541:44: note: in instantiation of member
      function 'tbb::interface6::internal::concrete_filter<void,
      std::__1::optional<int>, (lambda at
      /Users/ma/Codes/devs/grppi/include/tbb/parallel_execution_tbb.h:692:5)>::concrete_filter'
      requested here
        concrete_filter<T,U,Body>* f = new concrete_filter<T,U,Body>(mode,body);
                                           ^
/usr/local/include/tbb/pipeline.h:545:5: note: in instantiation of member
      function 'tbb::interface6::internal::filter_node_leaf<void,
      std::__1::optional<int>, (lambda at
      /Users/ma/Codes/devs/grppi/include/tbb/parallel_execution_tbb.h:692:5)>::add_to'
      requested here
    filter_node_leaf( tbb::filter::mode m, const Body& b ) : mode(m), body(b) {}
    ^
/usr/local/include/tbb/pipeline.h:574:16: note: in instantiation of member
      function 'tbb::interface6::internal::filter_node_leaf<void,
      std::__1::optional<int>, (lambda at
      /Users/ma/Codes/devs/grppi/include/tbb/parallel_execution_tbb.h:692:5)>::filter_node_leaf'
      requested here
    return new internal::filter_node_leaf<T,U,Body>(mode, body);
               ^
/Users/ma/Codes/devs/grppi/include/tbb/parallel_execution_tbb.h:690:25: note:
      (skipping 5 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see
      all)
  auto generator = tbb::make_filter<void, output_type>(
                        ^
/usr/local/include/gtest/internal/gtest-internal.h:672:42: note: in
      instantiation of member function
      'testing::internal::TestFactoryImpl<context_test_static_three_stages_farm_seq_Test<grppi::parallel_execution_tbb>
      >::CreateTest' requested here
        TestClass::TearDownTestCase, new TestFactoryImpl<TestClass>);
                                         ^
/usr/local/include/gtest/internal/gtest-internal.h:676:57: note: in
      instantiation of member function
      'testing::internal::TypeParameterizedTest<context_test,
      testing::internal::TemplateSel<context_test_static_three_stages_farm_seq_Test>,
      testing::internal::Types1<grppi::parallel_execution_tbb> >::Register'
      requested here
                                 typename Types::Tail>::Register(prefix,
                                                        ^
/usr/local/include/gtest/internal/gtest-internal.h:676:57: note: in
      instantiation of member function
      'testing::internal::TypeParameterizedTest<context_test,
      testing::internal::TemplateSel<context_test_static_three_stages_farm_seq_Test>,
      testing::internal::Types2<grppi::parallel_execution_omp,
      grppi::parallel_execution_tbb> >::Register' requested here
/usr/local/include/gtest/internal/gtest-internal.h:676:57: note: in
      instantiation of member function
      'testing::internal::TypeParameterizedTest<context_test,
      testing::internal::TemplateSel<context_test_static_three_stages_farm_seq_Test>,
      testing::internal::Types3<grppi::parallel_execution_native,
      grppi::parallel_execution_omp, grppi::parallel_execution_tbb> >::Register'
      requested here
/Users/ma/Codes/devs/grppi/unit_tests/context.cpp:706:1: note: in instantiation
      of member function 'testing::internal::TypeParameterizedTest<context_test,
      testing::internal::TemplateSel<context_test_static_three_stages_farm_seq_Test>,
      testing::internal::Types4<grppi::sequential_execution,
      grppi::parallel_execution_native, grppi::parallel_execution_omp,
      grppi::parallel_execution_tbb> >::Register' requested here
TYPED_TEST(context_test, static_three_stages_farm_seq)
^
/usr/local/include/gtest/gtest-typed-test.h:216:27: note: expanded from macro
      'TYPED_TEST'
              CaseName)>::Register("",                                        \
                          ^
/usr/local/include/tbb/pipeline.h:384:11: note: default constructor of '' is
      implicitly deleted because variant field 'actual_value' has a non-trivial
      default constructor
        T actual_value;
          ^
/usr/local/include/tbb/pipeline.h:400:30: error: call to implicitly-deleted
      default constructor of
      'tbb::interface6::internal::token_helper<std::__1::optional<int>,
      false>::type_to_void_ptr_map'
        type_to_void_ptr_map mymap;
                             ^
/usr/local/include/tbb/pipeline.h:416:42: note: in instantiation of member
      function 'tbb::interface6::internal::token_helper<std::__1::optional<int>,
      false>::cast_from_void_ptr' requested here
        t_pointer temp_input = t_helper::cast_from_void_ptr(input);
                                         ^
/usr/local/include/tbb/pipeline.h:428:5: note: in instantiation of member
      function
      'tbb::interface6::internal::concrete_filter<std::__1::optional<int>,
      std::__1::optional<int>, (lambda at
      /Users/ma/Codes/devs/grppi/include/tbb/parallel_execution_tbb.h:924:7)>::operator()'
      requested here
    concrete_filter(tbb::filter::mode filter_mode, const Body& body) : f...
    ^
/usr/local/include/tbb/pipeline.h:541:44: note: in instantiation of member
      function
      'tbb::interface6::internal::concrete_filter<std::__1::optional<int>,
      std::__1::optional<int>, (lambda at
      /Users/ma/Codes/devs/grppi/include/tbb/parallel_execution_tbb.h:924:7)>::concrete_filter'
      requested here
        concrete_filter<T,U,Body>* f = new concrete_filter<T,U,Body>(mode,body);
                                           ^
/usr/local/include/tbb/pipeline.h:545:5: note: in instantiation of member
      function
      'tbb::interface6::internal::filter_node_leaf<std::__1::optional<int>,
      std::__1::optional<int>, (lambda at
      /Users/ma/Codes/devs/grppi/include/tbb/parallel_execution_tbb.h:924:7)>::add_to'
      requested here
    filter_node_leaf( tbb::filter::mode m, const Body& b ) : mode(m), body(b) {}
    ^
/usr/local/include/tbb/pipeline.h:574:16: note: in instantiation of member
      function
      'tbb::interface6::internal::filter_node_leaf<std::__1::optional<int>,
      std::__1::optional<int>, (lambda at
      /Users/ma/Codes/devs/grppi/include/tbb/parallel_execution_tbb.h:924:7)>::filter_node_leaf'
      requested here
    return new internal::filter_node_leaf<T,U,Body>(mode, body);
               ^
/Users/ma/Codes/devs/grppi/include/tbb/parallel_execution_tbb.h:922:15: note:
      (skipping 5 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see
      all)
  return tbb::make_filter<input_type, output_type>(
              ^
/usr/local/include/gtest/internal/gtest-internal.h:672:42: note: in
      instantiation of member function
      'testing::internal::TestFactoryImpl<context_test_static_three_stages_farm_seq_Test<grppi::parallel_execution_tbb>
      >::CreateTest' requested here
        TestClass::TearDownTestCase, new TestFactoryImpl<TestClass>);
                                         ^
/usr/local/include/gtest/internal/gtest-internal.h:676:57: note: in
      instantiation of member function
      'testing::internal::TypeParameterizedTest<context_test,
      testing::internal::TemplateSel<context_test_static_three_stages_farm_seq_Test>,
      testing::internal::Types1<grppi::parallel_execution_tbb> >::Register'
      requested here
                                 typename Types::Tail>::Register(prefix,
                                                        ^
/usr/local/include/gtest/internal/gtest-internal.h:676:57: note: in
      instantiation of member function
      'testing::internal::TypeParameterizedTest<context_test,
      testing::internal::TemplateSel<context_test_static_three_stages_farm_seq_Test>,
      testing::internal::Types2<grppi::parallel_execution_omp,
      grppi::parallel_execution_tbb> >::Register' requested here
/usr/local/include/gtest/internal/gtest-internal.h:676:57: note: in
      instantiation of member function
      'testing::internal::TypeParameterizedTest<context_test,
      testing::internal::TemplateSel<context_test_static_three_stages_farm_seq_Test>,
      testing::internal::Types3<grppi::parallel_execution_native,
      grppi::parallel_execution_omp, grppi::parallel_execution_tbb> >::Register'
      requested here
/Users/ma/Codes/devs/grppi/unit_tests/context.cpp:706:1: note: in instantiation
      of member function 'testing::internal::TypeParameterizedTest<context_test,
      testing::internal::TemplateSel<context_test_static_three_stages_farm_seq_Test>,
      testing::internal::Types4<grppi::sequential_execution,
      grppi::parallel_execution_native, grppi::parallel_execution_omp,
      grppi::parallel_execution_tbb> >::Register' requested here
TYPED_TEST(context_test, static_three_stages_farm_seq)
^
/usr/local/include/gtest/gtest-typed-test.h:216:27: note: expanded from macro
      'TYPED_TEST'
              CaseName)>::Register("",                                        \
                          ^
/usr/local/include/tbb/pipeline.h:384:11: note: default constructor of '' is
      implicitly deleted because variant field 'actual_value' has a non-trivial
      default constructor
        T actual_value;
          ^
3 errors generated.
make[2]: *** [unit_tests/CMakeFiles/utest_grppi.dir/context.cpp.o] Error 1
make[1]: *** [unit_tests/CMakeFiles/utest_grppi.dir/all] Error 2
make: *** [all] Error 2
```
From reading the message, it seems that the problem is due to the fact that TBB does not like some aspects of the std::optional implementation in Clang 7.0.

Disabling TBB will make all the unit tests and samples compiled successfully and run correctly.

**Comment by tete17** [comment]
Regarding the first error I am a bit confused the macro `TYPED_TEST_CASE` is not variadic in my googletest implementation. 

What version are you using?

Regarding the actual error:

After doing some digging, turns out there is a discrepancy between libstdc++ and libc++ in the default constructor of `std::optional`

 * libc++ file: http://llvm.org/viewvc/llvm-project/libcxx/trunk/include/optional?view=markup line: 686
   `constexpr optional() noexcept {}`
 * libstdc++ line: 478
  `constexpr optional() = default;`

To me that means that the stdc++ version is non trivially constructable because it has a user defined construct while the one of libstdc++ is. (I may be wrong on this please double check).

This then means that a union can not be trivially constructed on libc++ and that is something that TBB seems to require??? Please @jdgarciauc3m maybe you could give more insight into this since I am not familiar with TBB.

The issue is that it looks like we are relaying on libstdc++ behaviour even though is the incorrect one and libc++ is right.

I have cooked up an example on compiler explorer so you can see what I am talking
https://godbolt.org/z/kch7sd

**Comment by Jerry-Ma** [comment]
I am using gtest 1.8.0 from homebrew. `TPED_TEST_CASE` is defined in https://github.com/google/googletest/blob/v1.8.x/googletest/include/gtest/gtest-typed-test.h line 194.

I believe you are right about the difference of the std::optional implementation in clang and gcc, and I learned quite a bit after reading the relevant articles and SO questions.

I hope there is an easy fix of this this problem, which unfortunately is beyond my level of C++. In any case, for now, I am disabling TBB so it is not critical to me.

**Comment by soroshsabz** [comment]
ITNOA

@jdgarciauc3m 

any update?

**Comment by tete17** [comment]
¿¿ITNOA??

**Comment by jdgarciauc3m** [comment]
Sorry for the long delay.

We are now back.

I am closing this pull-request. The optional issue is now solved by pull request #369.

**Pull request closed without merging**
