### PR TITLE
Add unit tests for farm - Issue 93

### PR DESCRIPTION
**Pull request by javidoc00**
Added unit tests for the farm pattern. Poly tests are commented.

### CODE REVIEW

**Review by jdgarciauc3m — CHANGES_REQUESTED** [review]
After updating with latest tests do not pass:

The following tests FAILED:
	 40 - farm_test/*.static_multiple_sink (Failed)
	 41 - farm_test/*.static_multiple_ary_sink (Failed)
	 43 - farm_test/*.static_single_composed (SEGFAULT)
	 44 - farm_test/*.static_multiple_composed (SEGFAULT)

**Comment by AndresSanchezCuadrado** [comment]
This pull request has a dependency with issue #195: "Update polymorphic version of farm pattern".

**Review by jdgarciauc3m — APPROVED** [review]
OK

**Comment by jdgarciauc3m** [comment]
Solved issue #93

**Pull request merged**
