### PR TITLE
 Complete the interface in the poly directory - issue 90

### PR DESCRIPTION
**Pull request by AndresSanchezCuadrado**
Polymorphic farm.

### CODE REVIEW

**Review by jdgarciauc3m — COMMENTED** [review]
This is the right direction.

However we need to complete the whole interface.

**Comment by AndresSanchezCuadrado** [comment]
I'm doing it right now. 
Maybe I will need some help with some of the patterns, but at the moment I'm making progress.

**Comment by jdgarciauc3m** [comment]
We will not be able to merge this branch unitl we have unit tests. Otherwise we cannot check this stuff.

**Review by jdgarciauc3m — APPROVED** [review]
OK. I know some things are not yet tested. We will solve issues during unit testing.

**Comment by jdgarciauc3m** [comment]
Solves issue #90

**Pull request merged**
