### PR TITLE
Add unit tests for reduce - Issue 96

### PR DESCRIPTION
**Pull request by AndresSanchezCuadrado**
Added unit test for reduce

### CODE REVIEW

**Review by jdgarciauc3m — CHANGES_REQUESTED** [review]
You are trying to merge with master?

**Comment by AndresSanchezCuadrado** [comment]
Yes I choose the wrong base. Now the base branch is latest.

**Comment by AndresSanchezCuadrado** [comment]
Requires branch of issue #121 to be merged in order to update the tests.

**Comment by jdgarciauc3m** [comment]
Static tests completed.

Poly tests to be addressed later.

**Comment by jdgarciauc3m** [comment]
This is issue #96

**Review by jdgarciauc3m — APPROVED** [review]

**Pull request merged**
