### PR TITLE
Range mapping

### PR DESCRIPTION
**Pull request by jdgarciauc3m**
Added new overloads of map, reduce, map/reduce, and stencil that accept a range. A range is any type having a begin(), end(), and size().

This allows to pass containers directly to the patterns.

### CODE REVIEW

**Review by javiergarcia — APPROVED** [review]

**Comment by tete17** [comment]
I think the use of external functions of `begin(containter)` and `end(container)` is preferred over the function members.

Rerf: https://stackoverflow.com/questions/7593086/why-use-non-member-begin-and-end-functions-in-c11

**Comment by jdgarciauc3m** [comment]
The use of global `std::begin()` over member `begin()` would allow to use as a range a primitive array whose size is known at compile time. This does not seem compelling enough to me. Such arrays would only emerge if they are defined on stack (small sizes) or as globals.

Any other use case?

**Review by Drioastorga — APPROVED** [review]
Ok

**Review by mdolz — COMMENTED** [review]
Ok.

**Review by mdolz — APPROVED** [review]
Ok.

**Comment by tete17** [comment]
I think the idea behind `std::begin()` and `std::end()` is to be more flexible. It is easier to implement an external function to adapt a third party container that having to inherited and then define a member function.

It is also recommended by the author of "Simplify c++"
[https://arne-mertz.de/2015/07/new-c-features-stdbeginend-and-range-based-for-loops/ ](url)

**Comment by jdgarciauc3m** [comment]
Solves issue #77

**Pull request merged**
