### PR TITLE
Applied Apache 2.0 license

### PR DESCRIPTION
**Pull request by jdgarciauc3m**
We are moving to Apache 2.0 license.

### CODE REVIEW

**Review by javiergarcia — APPROVED** [review]
Agree

**Review by Drioastorga — APPROVED** [review]
Agree.

**Review by mdolz — APPROVED** [review]
Agree.

**Review by javidoc00 — COMMENTED** [review]
OK

**Review by javidoc00 — APPROVED** [review]
OK

**Pull request merged**
