### PR TITLE
Enable all warnings

### PR DESCRIPTION
**Pull request by jdgarciauc3m**
Enable maximum warning level and double check that code is warning free in clang and gcc.

This covers issue #76

### CODE REVIEW

**Review by Drioastorga — CHANGES_REQUESTED** [review]
Stencil pattern TBB implementation throws an error by a unused variable 'seq'. 

constexpr sequential_execution seq{};

**Comment by jdgarciauc3m** [comment]
Please, provide compiler and version.

**Comment by Drioastorga** [comment]
Compiling with gcc 6.3.0 emits multiple errors related to google test source code.

Error example:
```
GitHub/grppi/build/external/googletest/include/gtest/internal/gtest-port.h: In copy constructor ‘testing::internal::RE::RE(const testing::internal::RE&)’:
GitHub/grppi/build/external/googletest/include/gtest/internal/gtest-port.h:1160:3: error: ‘testing::internal::RE::pattern_’ should be initialized in the member initialization list [-Werror=effc++]
   RE(const RE& other) { Init(other.pattern()); }
```

**Review by Drioastorga — CHANGES_REQUESTED** [review]
See comments

**Comment by jdgarciauc3m** [comment]
Please, double check that you are using googletest 1.8 or later.

You can obtain googletest from https://github.com/google/googletest

**Review by Drioastorga — APPROVED** [review]
Ok. The problem was related to the google test version. Maybe we should check google test version.

**Comment by jdgarciauc3m** [comment]
This solves issue #76

**Pull request merged**
