### PR TITLE
Add unit tests for divide_and_conquer() - issue 92

### PR DESCRIPTION
**Pull request by AndresSanchezCuadrado**
Included polymorphic versions of the unit tests.

### CODE REVIEW

**Review by jdgarciauc3m — CHANGES_REQUESTED** [review]
Poly version do not return a value but have a return type.

This leads to undefined behavior.

**Comment by AndresSanchezCuadrado** [comment]
Fixed in issue #184.

**Review by jdgarciauc3m — APPROVED** [review]
OK

**Comment by jdgarciauc3m** [comment]
Solves issue #92

**Pull request merged**
