### PR TITLE
Full review of divide/conquer documentation - Issue 165

### PR DESCRIPTION
**Pull request by jdgarciauc3m**
* Documented the divide/conquer API.
* Minor edits to code.
* Also need to check that md documentation in doc directory is consistent.

### CODE REVIEW

**Review by mdolz — CHANGES_REQUESTED** [review]
$ make doc_doxygen

throws this error:

Error copying file "/home/mdolz/grppi-github/grppi/build/doc/html/map-pattern.html" to "/home/mdolz/grppi-github/grppi/build/doc/html/map_8md.html".
make[3]: *** [doxy/CMakeFiles/doc_doxygen] Error 1
make[2]: *** [doxy/CMakeFiles/doc_doxygen.dir/all] Error 2
make[1]: *** [doxy/CMakeFiles/doc_doxygen.dir/rule] Error 2
make: *** [doc_doxygen] Error 2

**Comment by jdgarciauc3m** [comment]
Make sure you have a clean copy of the branch.

**Comment by mdolz** [comment]
Changes requested:
- "... problem si obtained." -> "... problem is obtained."
- "... provided by function ..." -> " ...  provided by the function ..."
- "Applies de divide/conquer ..." -> "Applies the divide/conquer ..."
- " ... a solution.." -> " ... a solution."
- " ... elements of divide/conquer pattern ..." -> "... elements of the divide/conquer pattern ..."
- " ... that takes problem ..." -> "... that takes a problem ..."
- " ... returns collection ..." -> "...  returns a collection ..."
- This sentence sounds much better if it is merged with the next one: "A Divider is any C++ callable entity that takes problem and returns collection of solutions. The signature of the divider takes as argument the problem and returns a collection of suproblems." -> "A Divider is any C++ callable entity that takes a problem and returns a collection of suproblems."
- "... into subproblems the divider ..." -> "...  into subproblems, the divider ..."
- "... combiner taks two ..." -> "...  combiner takes two ..."
- "Example: Missing example" -> What does it mean?
- The code contains several errors:
  - mak_pair  -> make_pair
  - missing comma after the fourth argument
  - mid = first + distance(first,last)/2; -> mid = r.first + distance(r.first,r.last)/2;
  - etc.

**Review by javidoc00 — CHANGES_REQUESTED** [review]
There are errors compiling the example:
     - "mak_pair" has to be "make_pair"
     -  in function divide (range r) both "first" and "last" are  attributes or "range r"

**Review by Drioastorga — CHANGES_REQUESTED** [review]
The code example does not compile and contains multiple errors. 

For example in function divide:

return { make_pair(first,mid), mak_pair(mid+1,last) }; 

this line returns a vector of pair but the return type is a range, so the correct line should be:
return {range{r.first, r.mid} , range{r.mid+1,r.last}}  

There is a missing comma after the solver lambda.

**Comment by jdgarciauc3m** [comment]
New version needs review

**Review by mdolz — APPROVED** [review]

**Review by Drioastorga — APPROVED** [review]

**Review by javidoc00 — APPROVED** [review]

**Comment by jdgarciauc3m** [comment]
Solved issue #165

**Pull request merged**
