### PR TITLE
Reordered arguments of stream_reduce - Issue 238

### PR DESCRIPTION
**Pull request by mdolz**
Reordered arguments of stream_reduce as requested by issue #238:
```
auto r = stream_reduce(exec, 
  windowsize, offset, identity,
  generator,
  combiner,
  consumer);
```

### CODE REVIEW

**Review by jdgarciauc3m — CHANGES_REQUESTED** [review]
Please, as part of this issue also write the user documentation at `doc/stream-reduce.md`

**Comment by mdolz** [comment]
Done.

**Review by jdgarciauc3m — DISMISSED** [review]
OK

**Review by jdgarciauc3m — APPROVED** [review]
OK

**Comment by jdgarciauc3m** [comment]
Solves issue #238

**Pull request merged**
