### PR TITLE
Add unit tests for stencil() - issue 97

### PR DESCRIPTION
**Pull request by AndresSanchezCuadrado**
unit test stencil

### CODE REVIEW

**Review by jdgarciauc3m — CHANGES_REQUESTED** [review]
Branch issue-97 does not compile.

**Comment by AndresSanchezCuadrado** [comment]
Requires issue #152 to be merged in order to compile successfully

**Comment by AndresSanchezCuadrado** [comment]
Solved dependencies with issue #152.
Working properly.

**Review by jdgarciauc3m — CHANGES_REQUESTED** [review]
Tests for poly executions are missing.

**Review by jdgarciauc3m — APPROVED** [review]
OK

**Comment by jdgarciauc3m** [comment]
Solves issue #97

**Pull request merged**
