### PR TITLE
Revised stream reduce pattern - issue 127

### PR DESCRIPTION
**Pull request by Drioastorga**
Removed stream reduce interfaces that collapse the whole stream into a single value.

Changes:
- Now there is only one interface for the stream reduce. The interfaces that collapse the whole stream into a single value have been removed.
- The examples for the removed interfaces have been deleted.

### CODE REVIEW

**Review by jdgarciauc3m — APPROVED** [review]
OK

**Review by jdgarciauc3m — CHANGES_REQUESTED** [review]
Does not compile.

**Comment by Drioastorga** [comment]
I have removed the legacy google tests related to the deleted interfaces that collapses the whole stream into a single value.

**Review by jdgarciauc3m — APPROVED** [review]
OK

**Comment by jdgarciauc3m** [comment]
Solves issue #127

**Pull request merged**
