### PR TITLE
Moved execution policies - Issue 232

### PR DESCRIPTION
**Pull request by Drioastorga**
The execution policy header files have been moved to their corresponding directories and their include guards have been accordingly renamed.

### CODE REVIEW

**Comment by jdgarciauc3m** [comment]
This is issue #232

**Review by jdgarciauc3m — CHANGES_REQUESTED** [review]
Can we just include the policies from the specific files that really need them and avoid them in the general files

Example: include/seq/sequential_execution.h should be included from include/seq/map.h and not from include/map.h

**Comment by Drioastorga** [comment]
I have moved the includes from the generic pattern header file to their corresponding specific header files. Also, I have moved the support includes to the polymorphic pattern header files.

**Review by jdgarciauc3m — APPROVED** [review]
OK

**Comment by jdgarciauc3m** [comment]
Solves issue #232

**Pull request merged**
