### PR TITLE
Modified mapreduce to support identity argument - issue 214

### PR DESCRIPTION
**Pull request by mdolz**
Modified mapreduce interface and tests to support identity argument.

### CODE REVIEW

**Review by jdgarciauc3m — CHANGES_REQUESTED** [review]
For consistency with reduce(), the identity argument should go before the transform_op argument

**Comment by mdolz** [comment]
Fixed.

**Review by jdgarciauc3m — CHANGES_REQUESTED** [review]
The suffix Type should not be used for a type. 

Use Identity instead.

**Comment by mdolz** [comment]
Fixed.

**Review by jdgarciauc3m — CHANGES_REQUESTED** [review]
Rename argument name from `init`to `identity`.

It is not an initial value.

**Comment by mdolz** [comment]
Fixed.

**Review by jdgarciauc3m — APPROVED** [review]
OK

**Comment by jdgarciauc3m** [comment]
Solves issue #214

**Pull request merged**
